In [24]:
import numpy as np
from numpy import genfromtxt
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()

# def run():

data=genfromtxt("C:/Users/aadit.sah/Downloads/training_ccpp_x_y_train.csv",delimiter=',',encoding="utf8")
x_test=genfromtxt("C:/Users/aadit.sah/Downloads/test_ccpp_x_test.csv",delimiter=',',encoding="utf8")
y=[]

x_train=data[:,:-1]
y_train=data[:,-1]

# print(x_train)
# print(y_train)


# x_test=np.array(x_test)
# zx=np.array([1,2,3,4])
# xz=np.array([2])
# (xz*zx)
# len(x_train)
import pandas as pd
df=pd.DataFrame(x_train)
# /df.columns = df.columns.astype(str)
for i in df:
    str1=str(i)+'_'+str(i)
    df[str1]=df[i]**2
    
df2=pd.DataFrame(x_test)
# /df.columns = df.columns.astype(str)
for i in df2:
    str1=str(i)+'_'+str(i)
    df2[str1]=df2[i]**2

# df.columns.map(type)
# for i in df:
#     str1=str(i)+'_'+str(i)+'_'+str(i)
#     df[str1]=df[i]**3


df.columns = df.columns.astype(str)
df2.columns = df2.columns.astype(str)
x_train=df.values
x_test=df2.values

scaler.fit(x_train)
x_train=scaler.transform(x_train)

x_test=scaler.transform(x_test)

y_train

array([482.26, 446.94, 452.56, ..., 437.65, 459.97, 444.42])

In [25]:
def step_grad(x_train,y_train,lr,m):
    l=len(m)
    M=len(x_train)
    m_slope=np.array(m)
    x=[]
    for i in range(M):
        x=np.append(x_train[i],[1])
        x=np.array(x)
        s=(m*x).sum()
        for j in range(len(x)):
            m_slope[j]+=(-2/M)*((y_train[i]-s))*x[j]
    new_m=m-lr*m_slope
#     print(new_m)
    return new_m    

In [11]:
# M=len(x_train)
# for i in range(M):
#     x=np.append(x_train[i],[1])
#     x=np.array(x)
# #     print(4*x)
#     s=(4*x).sum()
#     print(s)
    


In [26]:
def gd(x_train,y_train,learning_rate,num_iteration):
    n=len(x_train[1,:])
    array_m_c=np.zeros(n+1)
    for i in range(num_iteration):
        array_m_c=step_grad(x_train,y_train,learning_rate,array_m_c)
        print(i," cost ",cost(x_train,y_train,array_m_c))
    return array_m_c

In [27]:
def cost(x_train,y_train, m):
    total_cost = 0
    M = len(x_train)
    for i in range(M):
        x=np.append(x_train[i],[1])
        x=np.array(x)
        s=(m*x).sum()
        
        total_cost += (1/M)*((y_train[i]-s)**2)
    return total_cost

In [28]:
def run():
#     data = np.loadtxt("data.csv", delimiter=",")
    learning_rate = 0.1
    num_iterations = 800
#     x_train=data[:,:-1]
#     y_train=data[:,-1]
    m = gd(x_train,y_train, learning_rate, num_iterations)
    return m
#

In [29]:
def pred(x_test,a):
    l=len(x_test)
    xx=[]

    for i in range(l):
#         print(((a[:-1]*x_test[i,:]).sum())+a[-1])
        xx.append(((a[:-1]*x_test[i,:]).sum())+a[-1])
    return xx

In [23]:
y_train

array([482.26, 446.94, 452.56, ..., 437.65, 459.97, 444.42])

In [30]:
a=run()

# l=len(x_test)
# # # for i in range(l):
# # #     print(i)
# xx=[]

# for i in range(l):
#     print(((a[:-1]*x_test[i,:]).sum())+a[-1])
#     xx.append(((a[:-1]*x_test[i,:]).sum())+a[-1])
    
# xx
# m=np.array(a)
# m
jj=pred(x_train,a)
jj
# y_train




0  cost  132210.39964612355
1  cost  89998.39212413381
2  cost  65265.234485659515
3  cost  50312.50221992988
4  cost  41002.07613007063
5  cost  35051.43735322932
6  cost  31163.630748649233
7  cost  28578.191423565124
8  cost  26835.02027963086
9  cost  25647.43845464274
10  cost  24832.111773024153
11  cost  24269.203164257575
12  cost  23878.989925088204
13  cost  23607.705971928215
14  cost  23418.71439478654
15  cost  23286.858900321346
16  cost  23194.76984035144
17  cost  23130.405838546427
18  cost  23085.39535642905
19  cost  23053.9063772251
20  cost  23031.870170968683
21  cost  23016.445272067675
22  cost  23005.645859988537
23  cost  22998.083386930608
24  cost  22992.786579277545
25  cost  22989.075860247674
26  cost  22986.475651665165
27  cost  22984.653085505102
28  cost  22983.375150614116
29  cost  22982.47871879867
30  cost  22981.849574164105
31  cost  22981.407738742586
32  cost  22981.097202643086
33  cost  22980.878735986553
34  cost  22980.72485745356
35  cost

281  cost  22980.34371604879
282  cost  22980.343716048785
283  cost  22980.343716048785
284  cost  22980.343716048785
285  cost  22980.34371604879
286  cost  22980.343716048785
287  cost  22980.343716048785
288  cost  22980.343716048785
289  cost  22980.343716048785
290  cost  22980.343716048785
291  cost  22980.343716048785
292  cost  22980.343716048785
293  cost  22980.343716048785
294  cost  22980.343716048785
295  cost  22980.343716048785
296  cost  22980.343716048785
297  cost  22980.343716048785
298  cost  22980.343716048785
299  cost  22980.343716048785
300  cost  22980.343716048785
301  cost  22980.343716048785
302  cost  22980.343716048785
303  cost  22980.343716048785
304  cost  22980.343716048785
305  cost  22980.343716048785
306  cost  22980.343716048785
307  cost  22980.343716048785
308  cost  22980.343716048785
309  cost  22980.343716048785
310  cost  22980.343716048785
311  cost  22980.343716048785
312  cost  22980.343716048785
313  cost  22980.343716048785
314  cost  2

555  cost  22980.343716048785
556  cost  22980.343716048785
557  cost  22980.343716048785
558  cost  22980.343716048785
559  cost  22980.343716048785
560  cost  22980.343716048785
561  cost  22980.343716048785
562  cost  22980.343716048785
563  cost  22980.343716048785
564  cost  22980.343716048785
565  cost  22980.343716048785
566  cost  22980.343716048785
567  cost  22980.343716048785
568  cost  22980.343716048785
569  cost  22980.343716048785
570  cost  22980.343716048785
571  cost  22980.343716048785
572  cost  22980.343716048785
573  cost  22980.343716048785
574  cost  22980.343716048785
575  cost  22980.343716048785
576  cost  22980.343716048785
577  cost  22980.343716048785
578  cost  22980.343716048785
579  cost  22980.343716048785
580  cost  22980.343716048785
581  cost  22980.343716048785
582  cost  22980.343716048785
583  cost  22980.343716048785
584  cost  22980.343716048785
585  cost  22980.343716048785
586  cost  22980.343716048785
587  cost  22980.343716048785
588  cost 

[323.68931174913064,
 300.9191895016109,
 308.9163068392338,
 279.89374661119336,
 321.4024321091775,
 288.1684570607566,
 322.81651703155865,
 321.2482421493397,
 280.83808746596844,
 303.00569018198036,
 307.2095056603922,
 315.08607325538145,
 318.097741465036,
 328.9658723883778,
 318.07419348092793,
 279.7103959126923,
 312.68136826407704,
 296.07097405552105,
 305.8819777369436,
 287.13068479474833,
 292.349981137652,
 313.2327278478143,
 317.34756282784423,
 292.37969305435524,
 313.5074782773041,
 298.34694332875756,
 281.78909201050914,
 289.59319093903173,
 321.9985185046886,
 320.4347549510562,
 289.2456248079746,
 290.2114195719693,
 299.96880732634526,
 321.55572487171344,
 294.2983973665469,
 321.15586308638547,
 280.26660112359826,
 299.7559477933431,
 303.303626171533,
 309.4679940092715,
 315.58325659462963,
 294.93761476224347,
 313.57509706714086,
 293.88909583159256,
 314.4365039278097,
 323.5055473014547,
 289.72087747019293,
 308.74084888355833,
 282.3713932327474

In [31]:
kk=pred(x_test,a)
# x_test.shape,a.shape
kk

[318.3577313255098,
 317.9884863871723,
 283.08419111500666,
 306.3596816871868,
 313.40793444084136,
 298.24433748897604,
 324.3880339936491,
 294.7791121329771,
 325.7829242280973,
 289.3728525415795,
 285.9286113206539,
 284.63168212178755,
 319.1954611144335,
 313.91166264108364,
 295.49780705543606,
 306.9689991622314,
 325.00834350110523,
 295.3179764304763,
 277.96390151403887,
 288.80386927508914,
 291.4743284041008,
 322.3445675119654,
 307.067264243171,
 318.3639500329505,
 282.6206527458147,
 284.02940877887795,
 315.9248143025404,
 318.60162465145714,
 284.53126580168396,
 321.125307423795,
 290.6096717277507,
 282.40818375528943,
 297.7178095113197,
 317.7010243494742,
 317.49453457653794,
 318.97659393387505,
 298.5085486237037,
 305.0980703308449,
 292.28690516761725,
 323.76320156716054,
 314.7998812626176,
 285.18051691972596,
 319.4710424319752,
 317.51605676267434,
 307.7826756296276,
 321.41643752037504,
 289.4980525399217,
 279.3304333052698,
 289.20266600723414,
 

In [32]:
np.savetxt('C:/Users/aadit.sah/Downloads/PredictionGD2.csv',kk,delimiter=',',fmt='%1.10f')

In [79]:
# import numpy as np
# from sklearn import linear_model
# X = np.array([[-1, -1,3], [-2, -1,3], [1, 1,5], [2, 1,7]])
# Y = np.array([1, 1, 2, 2])
# clf = linear_model.SGDClassifier(max_iter=1000, tol=1e-3)
# clf.fit(X,Y)
# clf.fit(x_train,y_train)

ValueError: Unknown label type: (array([ 5. ,  5.6,  6.3,  7. ,  7.2,  7.4,  7.5,  8.1,  8.3,  8.4,  8.5,
        8.7,  8.8,  9.5,  9.6,  9.7, 10.4, 10.5, 10.8, 10.9, 11. , 11.3,
       11.5, 11.7, 11.8, 11.9, 12. , 12.1, 12.3, 12.5, 12.6, 12.7, 12.8,
       13.1, 13.2, 13.3, 13.4, 13.5, 13.6, 13.8, 13.9, 14. , 14.1, 14.2,
       14.3, 14.5, 14.6, 14.8, 14.9, 15. , 15.2, 15.3, 15.4, 15.6, 15.7,
       16. , 16.1, 16.2, 16.4, 16.5, 16.6, 16.7, 16.8, 17. , 17.1, 17.2,
       17.3, 17.4, 17.5, 17.6, 17.7, 17.8, 17.9, 18. , 18.1, 18.2, 18.3,
       18.4, 18.5, 18.7, 18.8, 18.9, 19. , 19.1, 19.2, 19.3, 19.4, 19.5,
       19.6, 19.7, 19.8, 19.9, 20. , 20.1, 20.2, 20.3, 20.4, 20.5, 20.6,
       20.7, 20.8, 20.9, 21. , 21.1, 21.2, 21.4, 21.5, 21.6, 21.7, 21.8,
       21.9, 22. , 22.1, 22.2, 22.3, 22.4, 22.5, 22.6, 22.7, 22.8, 22.9,
       23. , 23.1, 23.2, 23.3, 23.5, 23.7, 23.8, 23.9, 24. , 24.1, 24.2,
       24.3, 24.4, 24.5, 24.6, 24.7, 24.8, 25. , 25.1, 25.3, 26.2, 26.4,
       26.5, 26.6, 27. , 27.1, 27.5, 27.9, 28. , 28.2, 28.5, 28.7, 29. ,
       29.1, 29.6, 29.8, 29.9, 30.1, 30.5, 30.7, 30.8, 31. , 31.1, 31.2,
       31.5, 31.6, 31.7, 32. , 32.2, 32.5, 32.7, 32.9, 33. , 33.1, 33.2,
       33.3, 33.4, 34.6, 34.7, 34.9, 35.2, 35.4, 36. , 36.1, 36.2, 36.4,
       36.5, 37. , 37.2, 37.3, 37.6, 37.9, 38.7, 39.8, 41.7, 42.8, 43.1,
       43.5, 43.8, 44.8, 45.4, 46. , 46.7, 48.3, 48.8, 50. ]),)

In [32]:
y_train
y=np.array(y_train)
y

array([37.9, 21.4, 12.7, 19.9, 22.5, 32.7, 23.2, 21.5, 20.5, 33.3, 23.1,
       20. , 50. , 25. , 20.2, 16.4, 22.4, 20.4, 18.4, 37.3, 23.1, 34.7,
       33.1, 28.7, 15.6, 18.2, 17.2, 31.5, 26.6, 24.1, 22.3, 19.5, 36.1,
       17.6, 33.4,  8.8,  9.7, 13.4, 39.8, 24.4, 17.8, 24.3, 24. , 23.1,
       13.1, 16.7, 22.8, 27.5, 14.6, 13.4, 11. , 19.4, 15. , 44.8, 29.6,
       12.3, 24.6, 10.9, 28. , 30.8, 15.4, 18. , 35.2, 11.5, 19.5, 24.8,
       22.2, 20.1, 15.2, 50. , 17.1, 23. , 12. , 22. , 20. , 20.3, 17.2,
       37.2,  5. , 24.5, 18.9, 24.5, 24.8, 21.6,  7. , 17.7, 12.8, 14.9,
       18.3, 15.6, 19.9, 22.2, 16.7, 32.5, 25.1, 30.1, 16.1, 20.7, 46. ,
       22.3, 23. , 11.9, 23.3, 23.2, 22. , 10.5, 17.2, 29.8, 29. , 17.3,
       20.6, 20.1, 20.6, 17.8, 25. , 22.6, 18.7, 11.3,  9.6, 17.8, 23.9,
       38.7, 21.2, 25. , 28.5, 24. , 20.6,  5. , 22.9, 18.4, 31. , 36. ,
       20.8, 13.3, 23.2, 28.2, 43.8, 26.6, 23.9, 23.9, 27.9, 19.1, 30.5,
        8.3,  8.5, 16.5, 23.8, 19.6, 22.2, 24.3, 32